export   const songsList = [
    {
      video: "https://www.youtube.com/embed/8FAUEv_E_xQ",
      image: "https://www.mp3saavan.com/wp-content/uploads/2022/02/09221216-9377-40E7-81E6-A2C03B9B3F6E.png",
      title: "Arabic Kuthu",
      movie: "Beast",
      cast: "Vijay, Pooja Hegde",
      music: "Anirudh Ravichander",
      singers: "Anirudh Ravichander & Jonita Gandhi",
      lyrics: "SivaKarthikeyan",
    },
    {
      video: "https://www.youtube.com/embed/2VOL-VWXMnQ",
      image: "https://i.ytimg.com/vi/lsjfRhUlgjU/maxresdefault.jpg",
      title: "Jalabulajangu",
      movie: "Don",
      cast: " Sivakarthikeyan, Priyanka Mohan, SJ Suryah, Samuthirakani, Soori",
      music: "Anirudh Ravichander",
      singers: "Anirudh Ravichander",
      lyrics: "Rokesh",
    },
    {
      video: "https://www.youtube.com/embed/fRD_3vJagxk",
      image: "https://i.ytimg.com/vi/y5908Vg-0eM/maxresdefault.jpg",
      title: "Vaathi Coming",
      movie: "Master",
      cast: "Thalapathy Vijay ",
      music: "Anirudh Ravichander",
      singers: "Anirudh Ravichander & Gana Balachandar",
      lyrics: "Gana Balachandar",
    },
    {
      video: "https://www.youtube.com/embed/-0Za2uGiDLY",
      image: "https://i.ytimg.com/vi/-0Za2uGiDLY/maxresdefault.jpg",
      title: "Master Oh My Master",
      movie: "My Dear Bootham",
      cast: "",
      music: "Rajesh,D.Imman,",
      singers: "Benny Dayal",
      lyrics: "Yugabharathi",
    },
    {
      video: "https://www.youtube.com/embed/4QC-xQwldcQ",
      image: "https://a10.gaanacdn.com/gn_img/song/NOXWVRgWkq/XWV00YZ0Kk/size_m_1617267038.webp",
      title: "Jai Sulthan",
      movie: "Sulthan",
      cast: "Karthi, Rashmika Mandanna, Napoleon, Lal, Yogi Babu & others. ",
      music: "Vivek-Mervin ",
      singers: "Anirudh Ravichander, Junior Nithya & Gana Guna",
      lyrics: "Viveka, Thanikodi",
    },
    {
      video: "https://www.youtube.com/embed/x6Q7c9RyMzk",
      image: "https://i.ytimg.com/vi/x6Q7c9RyMzk/maxresdefault.jpg",
      title: "Rowdy Baby",
      movie: "Maari 2",
      cast: "Dhanush, Sai Pallavi",
      music: "Yuvan Shankar Raja",
      singers: "Dhanush & Dhee",
      lyrics: "Poetu Dhanush",
    },
    {
      video: "https://www.youtube.com/embed/xsbLtHql4g8",
      image: "https://static.toiimg.com/photo/msid-64645270/64645270.jpg",
      title: "Aalaporan Thamizhan",
      movie: "Mersal",
      cast: "Vijay",
      music: "A R Rahman",
      singers: "Kailash Kher, Sathya Prakash, Deepak, Pooja AV",
      lyrics: "Vivek ",
    },
    {
      video: "https://www.youtube.com/embed/ExVaiQ1xV5g",
      image: "https://i.ytimg.com/vi/VcmxGAYgxZk/maxresdefault.jpg",
      title: "Yaaro En Nenjai",
      movie: "Kutty",
      cast: "Dhanush, Shreya Saran",
      music: "Devi Sri Prasad",
      singers: " Sagar & Sumanga",
      lyrics: "Thamarai",
    }
  ];
  